openapi: 3.0.0
info:
  title: Learn Words
  description: a backend part of RSSchool Stage#2 task
  version: 1.0.0

servers:
  - url: /

components:
  schemas:
    Word:
      type: object
      properties:
        word:
          type: string
        image:
          type: string
        audio:
          type: string
        audioMeaning:
          type: string
        audioExample:
          type: string
        textMeaning:
          type: string
        textExample:
          type: string
        transcription:
          type: string
    WordCount:
      type: object
      properties:
        count:
          type: number
    Statistic:
      type: object
      properties:
        learnedWords:
          type: number
        optional:
          type: array
          items:
            type: any
#    User:
#      type: object
#      properties:
#        id:
#          type: string
#        name:
#          type: string
#        login:
#          type: string
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /words:
    parameters:
      - name: page
        in: query
        required: false
        description: Number of words / perPage = Total pages
        schema:
          type: string
      - name: perPage
        in: query
        required: false
        description: max number is 100
        schema:
          type: string
    get:
      tags:
        - words
      summary: Get a chunk words
      description: Gets a chink of words
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Word"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /words/count:
    get:
      tags:
        - words
      summary: Get a total number of words
      description: Get a total number of words
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/WordCount"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /statistics:
    get:
      tags:
        - Statistics
      summary: Get all statistics
      description: Gets all statistics
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Statistic"
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags:
        - Statistics
      summary: Create statistic
      description: Creates a new statistic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                learnedWords:
                  type: number
                  description: The number of the total learned words
                optional:
                  type: array
                  items:
                    type: any
      responses:
        200:
          description: The statistic has been created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Statistic"
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /statistics/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Statistics
      summary: Get statistic by id
      description: Gets a statistic by id
        e.g. “/statistics/123”
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Statistic"
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Statistic not found
    put:
      tags:
        - Statistics
      summary: Update a statistic
      description: Updates a statistic by id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: example
              properties:
                learnedWords:
                  type: number
                  description: The number of the total learned words
                optional:
                  type: array
                  items:
                    type: any
      responses:
        200:
          description: The statistic has been updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Statistic"
        400:
          description: Bad request
        401:
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      tags:
        - Statistics
      summary: Delete statistic
      description: Deletes statistic by id
      responses:
        204:
          description: The statistic has been deleted
        401:
          $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Statistic not found

#  /login:
#    post:
#      tags:
#        - Login
#      security:
#        []
#      summary: Login
#      description: Logins a user and returns a JWT-token
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              title: example
#              properties:
#                login:
#                  type: string
#                  description: Username
#                password:
#                  type: string
#                  description: Password
#              required:
#                - user
#                - login
#      responses:
#        200:
#          description: Successful login.
#          content:
#            application/json:
#              schema:
#                type: string
#                description: JWT Token
#        403:
#          description: Incorrect login or password
